// Generated by https://quicktype.io


// Generated by https://quicktype.io

export interface Auththen {
  msj:     string;
  data:    Data;
  errores: any[];
}

export interface Data {
  token:   string;
  usuario: Usuario;
}

export interface Usuario {
  nombreUsuario: string;
  correo:        string;
  tipoUsuario:   string;
  Permisos:      string;
}
