// Generated by https://quicktype.io

export interface TipUser {
  msj:     string;
  data:    Datum[];
  errores: any[];
}

export interface Datum {
  _id:             string;
  tipoUsuario:     string;
  nombreUsuario:   string;
  correo:          string;
  contrasenalogin: string;
  fallido:         number;
  estado:          string;
  createdAt:       string;
  updatedAt:       string;
  idusuario:       number;
  __v:             number;
}
