// Generated by https://quicktype.io

export interface EmpleadoByID {
  _id:            string;
  nombreCompleto: string;
  identidad:      number;
  numeroTelefono: string;
  correo:         string;
  createdAt:      string;
  updatedAt:      string;
  idempleado:     number;
  __v:            number;
}
