// Generated by https://quicktype.io

export interface Empleados2 {
    _id:            string;
    nombreCompleto: string;
    identidad:      number;
    numeroTelefono: string;
    correo:         string;
    createdAt:      string;
    updatedAt:      string;
    idempleado:     number;
    __v:            number;
}
