// Generated by https://quicktype.io

export interface FacturaID {
    _id:             string;
    idcliente:       string;
    nombreCliente:   string;
    metodoPago:      string;
    idPlan:          string;
    nombrePlan:      string;
    precioPlan:      number;
    idproducto?:     string;
    nombreProducto?: string;
    precioProducto?: number;
    subtotal:        number;
    descuento:       number;
    totalPagar:      number;
    fecha:           string;
    createdAt:       string;
    updatedAt:       string;
    numeroFactura:   number;
    __v:             number;
    CantidadProducto: number;
}
